// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: CommentAddAo.proto

package terry_proto_comment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CommentAddAo service

type CommentAddAoService interface {
	AddCommentInfo(ctx context.Context, in *AddCommentRequest, opts ...client.CallOption) (*AddCommentResponse, error)
}

type commentAddAoService struct {
	c    client.Client
	name string
}

func NewCommentAddAoService(name string, c client.Client) CommentAddAoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "terry.proto.comment"
	}
	return &commentAddAoService{
		c:    c,
		name: name,
	}
}

func (c *commentAddAoService) AddCommentInfo(ctx context.Context, in *AddCommentRequest, opts ...client.CallOption) (*AddCommentResponse, error) {
	req := c.c.NewRequest(c.name, "CommentAddAo.AddCommentInfo", in)
	out := new(AddCommentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CommentAddAo service

type CommentAddAoHandler interface {
	AddCommentInfo(context.Context, *AddCommentRequest, *AddCommentResponse) error
}

func RegisterCommentAddAoHandler(s server.Server, hdlr CommentAddAoHandler, opts ...server.HandlerOption) error {
	type commentAddAo interface {
		AddCommentInfo(ctx context.Context, in *AddCommentRequest, out *AddCommentResponse) error
	}
	type CommentAddAo struct {
		commentAddAo
	}
	h := &commentAddAoHandler{hdlr}
	return s.Handle(s.NewHandler(&CommentAddAo{h}, opts...))
}

type commentAddAoHandler struct {
	CommentAddAoHandler
}

func (h *commentAddAoHandler) AddCommentInfo(ctx context.Context, in *AddCommentRequest, out *AddCommentResponse) error {
	return h.CommentAddAoHandler.AddCommentInfo(ctx, in, out)
}
