// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CommentAddAo.proto

package terry_proto_comment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddCommentRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CommentId            uint64         `protobuf:"varint,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	UserId               uint64         `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string         `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	CommentText          string         `protobuf:"bytes,5,opt,name=commentText,proto3" json:"commentText,omitempty"`
	Stars                uint64         `protobuf:"varint,6,opt,name=stars,proto3" json:"stars,omitempty"`
	Fans                 string         `protobuf:"bytes,7,opt,name=fans,proto3" json:"fans,omitempty"`
	AddTime              string         `protobuf:"bytes,8,opt,name=addTime,proto3" json:"addTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddCommentRequest) Reset()         { *m = AddCommentRequest{} }
func (m *AddCommentRequest) String() string { return proto.CompactTextString(m) }
func (*AddCommentRequest) ProtoMessage()    {}
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efbb90869f06f459, []int{0}
}

func (m *AddCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommentRequest.Unmarshal(m, b)
}
func (m *AddCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommentRequest.Marshal(b, m, deterministic)
}
func (m *AddCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommentRequest.Merge(m, src)
}
func (m *AddCommentRequest) XXX_Size() int {
	return xxx_messageInfo_AddCommentRequest.Size(m)
}
func (m *AddCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommentRequest proto.InternalMessageInfo

func (m *AddCommentRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AddCommentRequest) GetCommentId() uint64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *AddCommentRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddCommentRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AddCommentRequest) GetCommentText() string {
	if m != nil {
		return m.CommentText
	}
	return ""
}

func (m *AddCommentRequest) GetStars() uint64 {
	if m != nil {
		return m.Stars
	}
	return 0
}

func (m *AddCommentRequest) GetFans() string {
	if m != nil {
		return m.Fans
	}
	return ""
}

func (m *AddCommentRequest) GetAddTime() string {
	if m != nil {
		return m.AddTime
	}
	return ""
}

type AddCommentResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddCommentResponse) Reset()         { *m = AddCommentResponse{} }
func (m *AddCommentResponse) String() string { return proto.CompactTextString(m) }
func (*AddCommentResponse) ProtoMessage()    {}
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efbb90869f06f459, []int{1}
}

func (m *AddCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommentResponse.Unmarshal(m, b)
}
func (m *AddCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommentResponse.Marshal(b, m, deterministic)
}
func (m *AddCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommentResponse.Merge(m, src)
}
func (m *AddCommentResponse) XXX_Size() int {
	return xxx_messageInfo_AddCommentResponse.Size(m)
}
func (m *AddCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommentResponse proto.InternalMessageInfo

func (m *AddCommentResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*AddCommentRequest)(nil), "terry.proto.comment.AddCommentRequest")
	proto.RegisterType((*AddCommentResponse)(nil), "terry.proto.comment.AddCommentResponse")
}

func init() { proto.RegisterFile("CommentAddAo.proto", fileDescriptor_efbb90869f06f459) }

var fileDescriptor_efbb90869f06f459 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x49, 0xd3, 0xf6, 0x5a, 0x21, 0x71, 0x20, 0x64, 0x45, 0x0c, 0x51, 0x90, 0x20,
	0x53, 0x86, 0xb2, 0xc1, 0x14, 0xb1, 0x90, 0x05, 0x89, 0xa8, 0x7f, 0xc0, 0xd4, 0x57, 0xc1, 0x10,
	0xbb, 0xd8, 0xae, 0x04, 0xbf, 0x80, 0xbf, 0x8d, 0x6a, 0x1b, 0x1a, 0x20, 0xa8, 0x9b, 0xdf, 0xbb,
	0xef, 0x5e, 0xa2, 0x77, 0x80, 0x77, 0xaa, 0x6d, 0x49, 0xda, 0x4a, 0x88, 0x4a, 0x95, 0x6b, 0xad,
	0xac, 0xc2, 0x13, 0x4b, 0x5a, 0xbf, 0x7b, 0x51, 0x2e, 0xfd, 0x3c, 0x9d, 0x6d, 0x41, 0x25, 0xbd,
	0x9b, 0x7f, 0x0c, 0xe0, 0xb8, 0x12, 0x22, 0x2c, 0x37, 0xf4, 0xba, 0x21, 0x63, 0xf1, 0x06, 0x92,
	0x67, 0xe2, 0x82, 0x34, 0x8b, 0xb2, 0xa8, 0x98, 0xce, 0xf3, 0xb2, 0x27, 0xa9, 0x0c, 0xf4, 0xbd,
	0x23, 0x9b, 0xb0, 0x81, 0xe7, 0x30, 0x09, 0x40, 0x2d, 0xd8, 0x20, 0x8b, 0x8a, 0xb8, 0xd9, 0x19,
	0x78, 0x06, 0xc9, 0xc6, 0x90, 0xae, 0x05, 0x3b, 0x74, 0xa3, 0xa0, 0x30, 0x85, 0xf1, 0xf6, 0xf5,
	0xc0, 0x5b, 0x62, 0x71, 0x16, 0x15, 0x93, 0xe6, 0x5b, 0x63, 0x06, 0xd3, 0x10, 0xb0, 0xa0, 0x37,
	0xcb, 0x86, 0x6e, 0xdc, 0xb5, 0xf0, 0x14, 0x86, 0xc6, 0x72, 0x6d, 0x58, 0xe2, 0x42, 0xbd, 0x40,
	0x84, 0x78, 0xc5, 0xa5, 0x61, 0x23, 0xb7, 0xe0, 0xde, 0xc8, 0x60, 0xc4, 0x85, 0x58, 0xbc, 0xb4,
	0xc4, 0xc6, 0xce, 0xfe, 0x92, 0xf9, 0x23, 0x60, 0xb7, 0x08, 0xb3, 0x56, 0xd2, 0x10, 0xde, 0xfe,
	0x6a, 0xe2, 0xe2, 0x9f, 0x26, 0x3c, 0xfe, 0xb3, 0x8a, 0xb9, 0x81, 0x59, 0xf7, 0x2a, 0xb8, 0x84,
	0xa3, 0xdd, 0x27, 0x6a, 0xb9, 0x52, 0x78, 0xd9, 0x1b, 0xf7, 0xe7, 0x20, 0xe9, 0xd5, 0x5e, 0xce,
	0xff, 0x40, 0x7e, 0xf0, 0x94, 0x38, 0xe6, 0xfa, 0x33, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x3d, 0x9f,
	0x03, 0x11, 0x02, 0x00, 0x00,
}
