// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Common.proto

package daniel_xproject_proto_renewal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Chn                  string   `protobuf:"bytes,1,opt,name=chn,proto3" json:"chn,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	PartnerId            string   `protobuf:"bytes,3,opt,name=partnerId,proto3" json:"partnerId,omitempty"`
	ClientType           string   `protobuf:"bytes,4,opt,name=clientType,proto3" json:"clientType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee72d9a89737215c, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetChn() string {
	if m != nil {
		return m.Chn
	}
	return ""
}

func (m *RequestHeader) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *RequestHeader) GetPartnerId() string {
	if m != nil {
		return m.PartnerId
	}
	return ""
}

func (m *RequestHeader) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

type ResponseHeader struct {
	ErrNo                uint32   `protobuf:"varint,1,opt,name=errNo,proto3" json:"errNo,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee72d9a89737215c, []int{1}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetErrNo() uint32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *ResponseHeader) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type RenewalDealInfo struct {
	DealId                           uint64   `protobuf:"varint,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	BdealId                          uint64   `protobuf:"varint,2,opt,name=bdeal_id,json=bdealId,proto3" json:"bdeal_id,omitempty"`
	DisdealId                        string   `protobuf:"bytes,3,opt,name=disdeal_id,json=disdealId,proto3" json:"disdeal_id,omitempty"`
	DealType                         uint32   `protobuf:"varint,4,opt,name=deal_type,json=dealType,proto3" json:"deal_type,omitempty"`
	InsuranceId                      uint64   `protobuf:"varint,5,opt,name=insurance_id,json=insuranceId,proto3" json:"insurance_id,omitempty"`
	GroupId                          uint64   `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ProductId                        uint64   `protobuf:"varint,7,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductTitle                     string   `protobuf:"bytes,8,opt,name=product_title,json=productTitle,proto3" json:"product_title,omitempty"`
	Uid                              uint64   `protobuf:"varint,9,opt,name=uid,proto3" json:"uid,omitempty"`
	CpsAgent                         uint64   `protobuf:"varint,10,opt,name=cps_agent,json=cpsAgent,proto3" json:"cps_agent,omitempty"`
	InsuranceSn                      string   `protobuf:"bytes,11,opt,name=insurance_sn,json=insuranceSn,proto3" json:"insurance_sn,omitempty"`
	InsuranceBenificiary             string   `protobuf:"bytes,12,opt,name=insurance_benificiary,json=insuranceBenificiary,proto3" json:"insurance_benificiary,omitempty"`
	InsuranceBenificiaryIdentity     string   `protobuf:"bytes,13,opt,name=insurance_benificiary_identity,json=insuranceBenificiaryIdentity,proto3" json:"insurance_benificiary_identity,omitempty"`
	InsuranceBenificiaryIdentityType uint64   `protobuf:"varint,14,opt,name=insurance_benificiary_identity_type,json=insuranceBenificiaryIdentityType,proto3" json:"insurance_benificiary_identity_type,omitempty"`
	InsuranceBenificiarySex          uint32   `protobuf:"varint,15,opt,name=insurance_benificiary_sex,json=insuranceBenificiarySex,proto3" json:"insurance_benificiary_sex,omitempty"`
	InsuranceBenificiaryBirth        string   `protobuf:"bytes,16,opt,name=insurance_benificiary_birth,json=insuranceBenificiaryBirth,proto3" json:"insurance_benificiary_birth,omitempty"`
	InsuranceBegtime                 uint64   `protobuf:"varint,17,opt,name=insurance_begtime,json=insuranceBegtime,proto3" json:"insurance_begtime,omitempty"`
	InsuranceEndtime                 uint64   `protobuf:"varint,18,opt,name=insurance_endtime,json=insuranceEndtime,proto3" json:"insurance_endtime,omitempty"`
	Chn                              string   `protobuf:"bytes,19,opt,name=chn,proto3" json:"chn,omitempty"`
	RenewDealId                      uint64   `protobuf:"varint,20,opt,name=renew_deal_id,json=renewDealId,proto3" json:"renew_deal_id,omitempty"`
	RenewBdealId                     uint64   `protobuf:"varint,21,opt,name=renew_bdeal_id,json=renewBdealId,proto3" json:"renew_bdeal_id,omitempty"`
	RenewDisdealId                   string   `protobuf:"bytes,22,opt,name=renew_disdeal_id,json=renewDisdealId,proto3" json:"renew_disdeal_id,omitempty"`
	RenewUid                         uint64   `protobuf:"varint,23,opt,name=renew_uid,json=renewUid,proto3" json:"renew_uid,omitempty"`
	RenewPayState                    uint32   `protobuf:"varint,24,opt,name=renew_pay_state,json=renewPayState,proto3" json:"renew_pay_state,omitempty"`
	HasBuy                           uint64   `protobuf:"varint,25,opt,name=has_buy,json=hasBuy,proto3" json:"has_buy,omitempty"`
	BuyDealId                        uint64   `protobuf:"varint,26,opt,name=buy_deal_id,json=buyDealId,proto3" json:"buy_deal_id,omitempty"`
	TouchState                       uint32   `protobuf:"varint,27,opt,name=touch_state,json=touchState,proto3" json:"touch_state,omitempty"`
	TouchTimes                       uint32   `protobuf:"varint,28,opt,name=touch_times,json=touchTimes,proto3" json:"touch_times,omitempty"`
	TouchTime_1                      string   `protobuf:"bytes,29,opt,name=touch_time_1,json=touchTime1,proto3" json:"touch_time_1,omitempty"`
	TouchTime_2                      string   `protobuf:"bytes,30,opt,name=touch_time_2,json=touchTime2,proto3" json:"touch_time_2,omitempty"`
	TouchTime_3                      string   `protobuf:"bytes,31,opt,name=touch_time_3,json=touchTime3,proto3" json:"touch_time_3,omitempty"`
	TouchTime_4                      string   `protobuf:"bytes,32,opt,name=touch_time_4,json=touchTime4,proto3" json:"touch_time_4,omitempty"`
	TouchTime_5                      string   `protobuf:"bytes,33,opt,name=touch_time_5,json=touchTime5,proto3" json:"touch_time_5,omitempty"`
	FitRenewalPlanId                 uint32   `protobuf:"varint,34,opt,name=fit_renewal_plan_id,json=fitRenewalPlanId,proto3" json:"fit_renewal_plan_id,omitempty"`
	FitRenewalTitle                  string   `protobuf:"bytes,35,opt,name=fit_renewal_title,json=fitRenewalTitle,proto3" json:"fit_renewal_title,omitempty"`
	Cooperator                       uint32   `protobuf:"varint,36,opt,name=cooperator,proto3" json:"cooperator,omitempty"`
	CompanyPicurl                    string   `protobuf:"bytes,37,opt,name=company_picurl,json=companyPicurl,proto3" json:"company_picurl,omitempty"`
	InsurancePrice                   uint32   `protobuf:"varint,38,opt,name=insurance_price,json=insurancePrice,proto3" json:"insurance_price,omitempty"`
	InsuranceRealEndtime             uint64   `protobuf:"varint,39,opt,name=insurance_real_endtime,json=insuranceRealEndtime,proto3" json:"insurance_real_endtime,omitempty"`
	ModifyUser                       string   `protobuf:"bytes,40,opt,name=modify_user,json=modifyUser,proto3" json:"modify_user,omitempty"`
	Addtime                          uint64   `protobuf:"varint,41,opt,name=addtime,proto3" json:"addtime,omitempty"`
	Mtime                            string   `protobuf:"bytes,42,opt,name=mtime,proto3" json:"mtime,omitempty"`
	XXX_NoUnkeyedLiteral             struct{} `json:"-"`
	XXX_unrecognized                 []byte   `json:"-"`
	XXX_sizecache                    int32    `json:"-"`
}

func (m *RenewalDealInfo) Reset()         { *m = RenewalDealInfo{} }
func (m *RenewalDealInfo) String() string { return proto.CompactTextString(m) }
func (*RenewalDealInfo) ProtoMessage()    {}
func (*RenewalDealInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee72d9a89737215c, []int{2}
}

func (m *RenewalDealInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewalDealInfo.Unmarshal(m, b)
}
func (m *RenewalDealInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewalDealInfo.Marshal(b, m, deterministic)
}
func (m *RenewalDealInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewalDealInfo.Merge(m, src)
}
func (m *RenewalDealInfo) XXX_Size() int {
	return xxx_messageInfo_RenewalDealInfo.Size(m)
}
func (m *RenewalDealInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewalDealInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RenewalDealInfo proto.InternalMessageInfo

func (m *RenewalDealInfo) GetDealId() uint64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

func (m *RenewalDealInfo) GetBdealId() uint64 {
	if m != nil {
		return m.BdealId
	}
	return 0
}

func (m *RenewalDealInfo) GetDisdealId() string {
	if m != nil {
		return m.DisdealId
	}
	return ""
}

func (m *RenewalDealInfo) GetDealType() uint32 {
	if m != nil {
		return m.DealType
	}
	return 0
}

func (m *RenewalDealInfo) GetInsuranceId() uint64 {
	if m != nil {
		return m.InsuranceId
	}
	return 0
}

func (m *RenewalDealInfo) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *RenewalDealInfo) GetProductId() uint64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *RenewalDealInfo) GetProductTitle() string {
	if m != nil {
		return m.ProductTitle
	}
	return ""
}

func (m *RenewalDealInfo) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RenewalDealInfo) GetCpsAgent() uint64 {
	if m != nil {
		return m.CpsAgent
	}
	return 0
}

func (m *RenewalDealInfo) GetInsuranceSn() string {
	if m != nil {
		return m.InsuranceSn
	}
	return ""
}

func (m *RenewalDealInfo) GetInsuranceBenificiary() string {
	if m != nil {
		return m.InsuranceBenificiary
	}
	return ""
}

func (m *RenewalDealInfo) GetInsuranceBenificiaryIdentity() string {
	if m != nil {
		return m.InsuranceBenificiaryIdentity
	}
	return ""
}

func (m *RenewalDealInfo) GetInsuranceBenificiaryIdentityType() uint64 {
	if m != nil {
		return m.InsuranceBenificiaryIdentityType
	}
	return 0
}

func (m *RenewalDealInfo) GetInsuranceBenificiarySex() uint32 {
	if m != nil {
		return m.InsuranceBenificiarySex
	}
	return 0
}

func (m *RenewalDealInfo) GetInsuranceBenificiaryBirth() string {
	if m != nil {
		return m.InsuranceBenificiaryBirth
	}
	return ""
}

func (m *RenewalDealInfo) GetInsuranceBegtime() uint64 {
	if m != nil {
		return m.InsuranceBegtime
	}
	return 0
}

func (m *RenewalDealInfo) GetInsuranceEndtime() uint64 {
	if m != nil {
		return m.InsuranceEndtime
	}
	return 0
}

func (m *RenewalDealInfo) GetChn() string {
	if m != nil {
		return m.Chn
	}
	return ""
}

func (m *RenewalDealInfo) GetRenewDealId() uint64 {
	if m != nil {
		return m.RenewDealId
	}
	return 0
}

func (m *RenewalDealInfo) GetRenewBdealId() uint64 {
	if m != nil {
		return m.RenewBdealId
	}
	return 0
}

func (m *RenewalDealInfo) GetRenewDisdealId() string {
	if m != nil {
		return m.RenewDisdealId
	}
	return ""
}

func (m *RenewalDealInfo) GetRenewUid() uint64 {
	if m != nil {
		return m.RenewUid
	}
	return 0
}

func (m *RenewalDealInfo) GetRenewPayState() uint32 {
	if m != nil {
		return m.RenewPayState
	}
	return 0
}

func (m *RenewalDealInfo) GetHasBuy() uint64 {
	if m != nil {
		return m.HasBuy
	}
	return 0
}

func (m *RenewalDealInfo) GetBuyDealId() uint64 {
	if m != nil {
		return m.BuyDealId
	}
	return 0
}

func (m *RenewalDealInfo) GetTouchState() uint32 {
	if m != nil {
		return m.TouchState
	}
	return 0
}

func (m *RenewalDealInfo) GetTouchTimes() uint32 {
	if m != nil {
		return m.TouchTimes
	}
	return 0
}

func (m *RenewalDealInfo) GetTouchTime_1() string {
	if m != nil {
		return m.TouchTime_1
	}
	return ""
}

func (m *RenewalDealInfo) GetTouchTime_2() string {
	if m != nil {
		return m.TouchTime_2
	}
	return ""
}

func (m *RenewalDealInfo) GetTouchTime_3() string {
	if m != nil {
		return m.TouchTime_3
	}
	return ""
}

func (m *RenewalDealInfo) GetTouchTime_4() string {
	if m != nil {
		return m.TouchTime_4
	}
	return ""
}

func (m *RenewalDealInfo) GetTouchTime_5() string {
	if m != nil {
		return m.TouchTime_5
	}
	return ""
}

func (m *RenewalDealInfo) GetFitRenewalPlanId() uint32 {
	if m != nil {
		return m.FitRenewalPlanId
	}
	return 0
}

func (m *RenewalDealInfo) GetFitRenewalTitle() string {
	if m != nil {
		return m.FitRenewalTitle
	}
	return ""
}

func (m *RenewalDealInfo) GetCooperator() uint32 {
	if m != nil {
		return m.Cooperator
	}
	return 0
}

func (m *RenewalDealInfo) GetCompanyPicurl() string {
	if m != nil {
		return m.CompanyPicurl
	}
	return ""
}

func (m *RenewalDealInfo) GetInsurancePrice() uint32 {
	if m != nil {
		return m.InsurancePrice
	}
	return 0
}

func (m *RenewalDealInfo) GetInsuranceRealEndtime() uint64 {
	if m != nil {
		return m.InsuranceRealEndtime
	}
	return 0
}

func (m *RenewalDealInfo) GetModifyUser() string {
	if m != nil {
		return m.ModifyUser
	}
	return ""
}

func (m *RenewalDealInfo) GetAddtime() uint64 {
	if m != nil {
		return m.Addtime
	}
	return 0
}

func (m *RenewalDealInfo) GetMtime() string {
	if m != nil {
		return m.Mtime
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "daniel.xproject.proto.renewal.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "daniel.xproject.proto.renewal.ResponseHeader")
	proto.RegisterType((*RenewalDealInfo)(nil), "daniel.xproject.proto.renewal.RenewalDealInfo")
}

func init() { proto.RegisterFile("Common.proto", fileDescriptor_ee72d9a89737215c) }

var fileDescriptor_ee72d9a89737215c = []byte{
	// 824 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x4b, 0x6f, 0x1b, 0x37,
	0x10, 0x46, 0x5e, 0xb6, 0x35, 0x7a, 0x9a, 0x71, 0x6c, 0xba, 0x7e, 0x46, 0xce, 0xc3, 0x4d, 0x51,
	0x03, 0x89, 0x9d, 0x4b, 0x0f, 0x01, 0xea, 0xba, 0x40, 0x75, 0x48, 0x61, 0xc8, 0xce, 0x79, 0x41,
	0xed, 0x8e, 0x24, 0x16, 0x2b, 0x72, 0x4b, 0x72, 0x11, 0xef, 0x2f, 0xeb, 0xdf, 0x2b, 0x38, 0xdc,
	0xd5, 0x2a, 0x0b, 0xc1, 0xb7, 0x9d, 0x6f, 0xbe, 0xf9, 0x86, 0x43, 0xce, 0xcc, 0x42, 0xe7, 0x0f,
	0xbd, 0x58, 0x68, 0x75, 0x91, 0x19, 0xed, 0x34, 0x3b, 0x4a, 0x84, 0x92, 0x98, 0x5e, 0x3c, 0x64,
	0x46, 0xff, 0x83, 0xb1, 0x0b, 0xf0, 0x85, 0x41, 0x85, 0xdf, 0x45, 0x3a, 0xfc, 0x0e, 0xdd, 0x31,
	0xfe, 0x9b, 0xa3, 0x75, 0x7f, 0xa1, 0x48, 0xd0, 0xb0, 0x01, 0x3c, 0x8b, 0xe7, 0x8a, 0x3f, 0x39,
	0x7d, 0x72, 0xde, 0x1a, 0xfb, 0x4f, 0xb6, 0x0b, 0x1b, 0x56, 0xe7, 0x26, 0x46, 0xfe, 0x94, 0xc0,
	0xd2, 0x62, 0x87, 0xd0, 0xca, 0x84, 0x71, 0x0a, 0xcd, 0x28, 0xe1, 0xcf, 0xc8, 0x55, 0x03, 0xec,
	0x18, 0x20, 0x4e, 0x25, 0x2a, 0x77, 0x5f, 0x64, 0xc8, 0x9f, 0x93, 0x7b, 0x05, 0x19, 0x7e, 0x81,
	0xde, 0x18, 0x6d, 0xa6, 0x95, 0xc5, 0x32, 0xf3, 0x0e, 0xbc, 0x40, 0x63, 0xfe, 0xd6, 0x94, 0xbb,
	0x3b, 0x0e, 0x86, 0xcf, 0x8e, 0xc6, 0x7c, 0xb5, 0xb3, 0x2a, 0x7b, 0xb0, 0x86, 0xff, 0x75, 0xa0,
	0x3f, 0x0e, 0x45, 0xdc, 0xa0, 0x48, 0x47, 0x6a, 0xaa, 0xd9, 0x1e, 0x6c, 0x26, 0x28, 0xd2, 0x48,
	0x26, 0xa4, 0xf1, 0x7c, 0xbc, 0xe1, 0xcd, 0x51, 0xc2, 0xf6, 0x61, 0x6b, 0x52, 0x79, 0x9e, 0x92,
	0x67, 0x73, 0x52, 0xba, 0x8e, 0x00, 0x12, 0x69, 0x2b, 0x67, 0x59, 0x46, 0x89, 0x8c, 0x12, 0x76,
	0x00, 0x2d, 0xf2, 0xb9, 0xaa, 0x8a, 0xee, 0x78, 0xcb, 0x03, 0xbe, 0x06, 0xf6, 0x1a, 0x3a, 0x52,
	0xd9, 0xdc, 0x08, 0x15, 0xa3, 0x8f, 0x7e, 0x41, 0xd2, 0xed, 0x25, 0x16, 0x32, 0xcf, 0x8c, 0xce,
	0x33, 0xef, 0xde, 0x08, 0x99, 0xc9, 0x0e, 0x99, 0x33, 0xa3, 0x93, 0x3c, 0x76, 0xde, 0xb9, 0x49,
	0xce, 0x56, 0x89, 0x8c, 0x12, 0x76, 0x06, 0xdd, 0xca, 0xed, 0xa4, 0x4b, 0x91, 0x6f, 0xd1, 0xd9,
	0x3a, 0x25, 0x78, 0xef, 0x31, 0xff, 0x5a, 0xb9, 0x4c, 0x78, 0x8b, 0x82, 0xfd, 0xa7, 0x3f, 0x70,
	0x9c, 0xd9, 0x48, 0xcc, 0x50, 0x39, 0x0e, 0x84, 0x6f, 0xc5, 0x99, 0xfd, 0xdd, 0xdb, 0x3f, 0x1e,
	0xd8, 0x2a, 0xde, 0x26, 0xc9, 0xfa, 0xc0, 0x77, 0x8a, 0x5d, 0xc2, 0xab, 0x9a, 0x32, 0x41, 0x25,
	0xa7, 0x32, 0x96, 0xc2, 0x14, 0xbc, 0x43, 0xdc, 0x9d, 0xa5, 0xf3, 0xba, 0xf6, 0xb1, 0x1b, 0x38,
	0x5e, 0x1b, 0x14, 0xc9, 0x04, 0x95, 0x93, 0xae, 0xe0, 0x5d, 0x8a, 0x3e, 0x5c, 0x17, 0x3d, 0x2a,
	0x39, 0xec, 0x2b, 0x9c, 0x3d, 0xae, 0x12, 0x5e, 0xa1, 0x47, 0x45, 0x9d, 0x3e, 0x26, 0x45, 0xaf,
	0xf3, 0x1b, 0xec, 0xaf, 0x97, 0xb3, 0xf8, 0xc0, 0xfb, 0xf4, 0x94, 0x7b, 0xeb, 0x44, 0xee, 0xf0,
	0x81, 0x7d, 0x81, 0x83, 0xf5, 0xb1, 0x13, 0x69, 0xdc, 0x9c, 0x0f, 0xa8, 0x9a, 0xfd, 0x75, 0xd1,
	0xd7, 0x9e, 0xc0, 0x7e, 0x81, 0xed, 0xd5, 0xf8, 0x99, 0x93, 0x0b, 0xe4, 0xdb, 0x74, 0xf0, 0xc1,
	0x4a, 0x14, 0xe1, 0x3f, 0x92, 0x51, 0x25, 0x44, 0x66, 0x0d, 0xf2, 0x9f, 0x01, 0xaf, 0xe6, 0xf3,
	0x65, 0x3d, 0x9f, 0x43, 0xe8, 0xd2, 0x34, 0x47, 0x55, 0x13, 0xef, 0x84, 0x36, 0x24, 0xf0, 0x26,
	0xb4, 0xf1, 0x1b, 0xe8, 0x05, 0xce, 0x72, 0x0c, 0x5e, 0x11, 0xa9, 0x43, 0xe8, 0x75, 0xd9, 0xec,
	0xe7, 0x30, 0x28, 0x95, 0xea, 0x89, 0xd8, 0xa5, 0x44, 0x21, 0xfa, 0x66, 0x75, 0x2c, 0x02, 0xd3,
	0x77, 0xdf, 0x5e, 0xe8, 0x32, 0x02, 0xbe, 0xc9, 0x84, 0xbd, 0x83, 0x7e, 0x70, 0x66, 0xa2, 0x88,
	0xac, 0x13, 0x0e, 0x39, 0xa7, 0xeb, 0x0e, 0xe7, 0xbc, 0x15, 0xc5, 0x9d, 0x07, 0xfd, 0xb8, 0xce,
	0x85, 0x8d, 0x26, 0x79, 0xc1, 0xf7, 0xc3, 0xb8, 0xce, 0x85, 0xbd, 0xce, 0x0b, 0x76, 0x0c, 0xed,
	0x49, 0x5e, 0x2c, 0xeb, 0xf9, 0x29, 0x8c, 0xc6, 0x24, 0x2f, 0xca, 0x6a, 0x4e, 0xa0, 0xed, 0x74,
	0x1e, 0xcf, 0x4b, 0xf1, 0x03, 0x12, 0x07, 0x82, 0x82, 0xf2, 0x92, 0xe0, 0xaf, 0xcc, 0xf2, 0xc3,
	0x15, 0xc2, 0xbd, 0x47, 0xd8, 0x29, 0x74, 0x6a, 0x42, 0xf4, 0x91, 0x1f, 0x85, 0xfd, 0xb4, 0x64,
	0x7c, 0x6c, 0x30, 0x3e, 0xf1, 0xe3, 0x06, 0xe3, 0x53, 0x83, 0x71, 0xc9, 0x4f, 0x1a, 0x8c, 0xcb,
	0x06, 0xe3, 0x8a, 0x9f, 0x36, 0x18, 0x57, 0x0d, 0xc6, 0x67, 0xfe, 0xba, 0xc1, 0xf8, 0xcc, 0x7e,
	0x85, 0x97, 0x53, 0xe9, 0xa2, 0x72, 0x5f, 0x47, 0x59, 0x2a, 0x94, 0xbf, 0x93, 0x21, 0x95, 0x34,
	0x98, 0x4a, 0x57, 0x2e, 0xc1, 0xdb, 0x54, 0xa8, 0x51, 0xc2, 0x3e, 0xc0, 0xf6, 0x2a, 0x3d, 0x6c,
	0x8e, 0x33, 0x52, 0xed, 0xd7, 0xe4, 0xb0, 0x3c, 0xfc, 0x8a, 0xd6, 0x3a, 0x43, 0x23, 0x9c, 0x36,
	0xfc, 0x4d, 0xb8, 0xa4, 0x1a, 0x61, 0x6f, 0xa1, 0x17, 0xeb, 0x45, 0x26, 0x54, 0x11, 0x65, 0x32,
	0xce, 0x4d, 0xca, 0xdf, 0x92, 0x50, 0xb7, 0x44, 0x6f, 0x09, 0x64, 0xef, 0xa1, 0x5f, 0xb7, 0x6f,
	0x66, 0x64, 0x8c, 0xfc, 0x1d, 0x69, 0xf5, 0x96, 0xf0, 0xad, 0x47, 0xd9, 0x15, 0xec, 0xd6, 0x44,
	0xe3, 0x1f, 0xb7, 0x6a, 0xf6, 0xf7, 0xf4, 0xc2, 0xf5, 0x6e, 0x19, 0xa3, 0x48, 0xab, 0x86, 0x3f,
	0x81, 0xf6, 0x42, 0x27, 0x72, 0x5a, 0x44, 0xb9, 0x45, 0xc3, 0xcf, 0xc3, 0x0d, 0x05, 0xe8, 0x9b,
	0x45, 0xc3, 0x38, 0x6c, 0x8a, 0x24, 0xe8, 0xfc, 0x1c, 0x36, 0x6c, 0x69, 0xfa, 0x3f, 0xca, 0x82,
	0xf0, 0x0f, 0x14, 0x14, 0x8c, 0xc9, 0x06, 0xfd, 0x01, 0x2f, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0x00, 0xdf, 0x84, 0xb9, 0x28, 0x07, 0x00, 0x00,
}
