// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RenewalDealReadAo.proto

package daniel_xproject_proto_renewal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RenewalDealId struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DealId               uint64         `protobuf:"varint,2,opt,name=dealId,proto3" json:"dealId,omitempty"`
	RealTime             bool           `protobuf:"varint,3,opt,name=realTime,proto3" json:"realTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RenewalDealId) Reset()         { *m = RenewalDealId{} }
func (m *RenewalDealId) String() string { return proto.CompactTextString(m) }
func (*RenewalDealId) ProtoMessage()    {}
func (*RenewalDealId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba8d5dec53772262, []int{0}
}

func (m *RenewalDealId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewalDealId.Unmarshal(m, b)
}
func (m *RenewalDealId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewalDealId.Marshal(b, m, deterministic)
}
func (m *RenewalDealId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewalDealId.Merge(m, src)
}
func (m *RenewalDealId) XXX_Size() int {
	return xxx_messageInfo_RenewalDealId.Size(m)
}
func (m *RenewalDealId) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewalDealId.DiscardUnknown(m)
}

var xxx_messageInfo_RenewalDealId proto.InternalMessageInfo

func (m *RenewalDealId) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RenewalDealId) GetDealId() uint64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

func (m *RenewalDealId) GetRealTime() bool {
	if m != nil {
		return m.RealTime
	}
	return false
}

type SingleRenewalDeal struct {
	Header               *ResponseHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RenewalDealInfo      *RenewalDealInfo `protobuf:"bytes,2,opt,name=renewalDealInfo,proto3" json:"renewalDealInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SingleRenewalDeal) Reset()         { *m = SingleRenewalDeal{} }
func (m *SingleRenewalDeal) String() string { return proto.CompactTextString(m) }
func (*SingleRenewalDeal) ProtoMessage()    {}
func (*SingleRenewalDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba8d5dec53772262, []int{1}
}

func (m *SingleRenewalDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleRenewalDeal.Unmarshal(m, b)
}
func (m *SingleRenewalDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleRenewalDeal.Marshal(b, m, deterministic)
}
func (m *SingleRenewalDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRenewalDeal.Merge(m, src)
}
func (m *SingleRenewalDeal) XXX_Size() int {
	return xxx_messageInfo_SingleRenewalDeal.Size(m)
}
func (m *SingleRenewalDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRenewalDeal.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRenewalDeal proto.InternalMessageInfo

func (m *SingleRenewalDeal) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SingleRenewalDeal) GetRenewalDealInfo() *RenewalDealInfo {
	if m != nil {
		return m.RenewalDealInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*RenewalDealId)(nil), "daniel.xproject.proto.renewal.RenewalDealId")
	proto.RegisterType((*SingleRenewalDeal)(nil), "daniel.xproject.proto.renewal.SingleRenewalDeal")
}

func init() { proto.RegisterFile("RenewalDealReadAo.proto", fileDescriptor_ba8d5dec53772262) }

var fileDescriptor_ba8d5dec53772262 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0f, 0x4a, 0xcd, 0x4b,
	0x2d, 0x4f, 0xcc, 0x71, 0x49, 0x4d, 0xcc, 0x09, 0x4a, 0x4d, 0x4c, 0x71, 0xcc, 0xd7, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4d, 0x49, 0xcc, 0xcb, 0x4c, 0xcd, 0xd1, 0xab, 0x28, 0x28, 0xca,
	0xcf, 0x4a, 0x4d, 0x2e, 0x81, 0x08, 0xeb, 0x15, 0x41, 0x94, 0x4b, 0xf1, 0x38, 0xe7, 0xe7, 0xe6,
	0xe6, 0xe7, 0x41, 0x44, 0x95, 0x3a, 0x19, 0xb9, 0x78, 0x91, 0x0c, 0xf2, 0x4c, 0x11, 0x72, 0xe1,
	0x62, 0xcb, 0x48, 0x4d, 0x4c, 0x49, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0xd2, 0xd1,
	0xc3, 0x6b, 0x9e, 0x5e, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x07, 0x58, 0x4f, 0x10, 0x54,
	0xaf, 0x90, 0x18, 0x17, 0x5b, 0x0a, 0xd8, 0x3c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x28,
	0x4f, 0x48, 0x8a, 0x8b, 0xa3, 0x28, 0x35, 0x31, 0x27, 0x24, 0x33, 0x37, 0x55, 0x82, 0x59, 0x81,
	0x51, 0x83, 0x23, 0x08, 0xce, 0x57, 0xda, 0xc2, 0xc8, 0x25, 0x18, 0x9c, 0x99, 0x97, 0x9e, 0x93,
	0x8a, 0xe4, 0x22, 0x21, 0x57, 0x34, 0xf7, 0xe8, 0x12, 0x74, 0x4f, 0x71, 0x41, 0x7e, 0x5e, 0x71,
	0x2a, 0x9a, 0x83, 0x22, 0xb8, 0xf8, 0x8b, 0x90, 0xfc, 0x99, 0x97, 0x96, 0x0f, 0x76, 0x19, 0xb7,
	0x91, 0x1e, 0x41, 0xf3, 0x50, 0x74, 0x05, 0xa1, 0x1b, 0x63, 0x34, 0x8d, 0x91, 0x4b, 0x02, 0x23,
	0x2e, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xaa, 0xb8, 0xc4, 0xdc, 0x53, 0x4b, 0x90,
	0xa4, 0x9d, 0x2a, 0xa1, 0xe1, 0xac, 0x43, 0x82, 0xbd, 0x29, 0x52, 0x06, 0x04, 0x54, 0x63, 0x84,
	0x9b, 0x12, 0x43, 0x12, 0x1b, 0x58, 0x89, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x5b, 0x64,
	0xf5, 0x2a, 0x02, 0x00, 0x00,
}
