// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: RenewalDealReadAo.proto

package daniel_xproject_proto_renewal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RenewalDealReadAoService service

type RenewalDealReadAoService interface {
	GetRenewalDealByDealId(ctx context.Context, in *RenewalDealId, opts ...client.CallOption) (*SingleRenewalDeal, error)
}

type renewalDealReadAoService struct {
	c    client.Client
	name string
}

func NewRenewalDealReadAoService(name string, c client.Client) RenewalDealReadAoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "daniel.xproject.proto.renewal"
	}
	return &renewalDealReadAoService{
		c:    c,
		name: name,
	}
}

func (c *renewalDealReadAoService) GetRenewalDealByDealId(ctx context.Context, in *RenewalDealId, opts ...client.CallOption) (*SingleRenewalDeal, error) {
	req := c.c.NewRequest(c.name, "RenewalDealReadAoService.GetRenewalDealByDealId", in)
	out := new(SingleRenewalDeal)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RenewalDealReadAoService service

type RenewalDealReadAoServiceHandler interface {
	GetRenewalDealByDealId(context.Context, *RenewalDealId, *SingleRenewalDeal) error
}

func RegisterRenewalDealReadAoServiceHandler(s server.Server, hdlr RenewalDealReadAoServiceHandler, opts ...server.HandlerOption) error {
	type renewalDealReadAoService interface {
		GetRenewalDealByDealId(ctx context.Context, in *RenewalDealId, out *SingleRenewalDeal) error
	}
	type RenewalDealReadAoService struct {
		renewalDealReadAoService
	}
	h := &renewalDealReadAoServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RenewalDealReadAoService{h}, opts...))
}

type renewalDealReadAoServiceHandler struct {
	RenewalDealReadAoServiceHandler
}

func (h *renewalDealReadAoServiceHandler) GetRenewalDealByDealId(ctx context.Context, in *RenewalDealId, out *SingleRenewalDeal) error {
	return h.RenewalDealReadAoServiceHandler.GetRenewalDealByDealId(ctx, in, out)
}
