// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RenewalReadAo.proto

package daniel_proto_renewal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRenewalRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DealId               uint64         `protobuf:"varint,2,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	RealTime             bool           `protobuf:"varint,3,opt,name=realTime,proto3" json:"realTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRenewalRequest) Reset()         { *m = GetRenewalRequest{} }
func (m *GetRenewalRequest) String() string { return proto.CompactTextString(m) }
func (*GetRenewalRequest) ProtoMessage()    {}
func (*GetRenewalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0181a2094d6fc8b9, []int{0}
}

func (m *GetRenewalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRenewalRequest.Unmarshal(m, b)
}
func (m *GetRenewalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRenewalRequest.Marshal(b, m, deterministic)
}
func (m *GetRenewalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRenewalRequest.Merge(m, src)
}
func (m *GetRenewalRequest) XXX_Size() int {
	return xxx_messageInfo_GetRenewalRequest.Size(m)
}
func (m *GetRenewalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRenewalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRenewalRequest proto.InternalMessageInfo

func (m *GetRenewalRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetRenewalRequest) GetDealId() uint64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

func (m *GetRenewalRequest) GetRealTime() bool {
	if m != nil {
		return m.RealTime
	}
	return false
}

type GetRenewalResponse struct {
	Header               *ResponseHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DealInfo             *RenewalDealInfo `protobuf:"bytes,2,opt,name=dealInfo,proto3" json:"dealInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetRenewalResponse) Reset()         { *m = GetRenewalResponse{} }
func (m *GetRenewalResponse) String() string { return proto.CompactTextString(m) }
func (*GetRenewalResponse) ProtoMessage()    {}
func (*GetRenewalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0181a2094d6fc8b9, []int{1}
}

func (m *GetRenewalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRenewalResponse.Unmarshal(m, b)
}
func (m *GetRenewalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRenewalResponse.Marshal(b, m, deterministic)
}
func (m *GetRenewalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRenewalResponse.Merge(m, src)
}
func (m *GetRenewalResponse) XXX_Size() int {
	return xxx_messageInfo_GetRenewalResponse.Size(m)
}
func (m *GetRenewalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRenewalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRenewalResponse proto.InternalMessageInfo

func (m *GetRenewalResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetRenewalResponse) GetDealInfo() *RenewalDealInfo {
	if m != nil {
		return m.DealInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRenewalRequest)(nil), "daniel.proto.renewal.GetRenewalRequest")
	proto.RegisterType((*GetRenewalResponse)(nil), "daniel.proto.renewal.GetRenewalResponse")
}

func init() { proto.RegisterFile("RenewalReadAo.proto", fileDescriptor_0181a2094d6fc8b9) }

var fileDescriptor_0181a2094d6fc8b9 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0e, 0x4a, 0xcd, 0x4b,
	0x2d, 0x4f, 0xcc, 0x09, 0x4a, 0x4d, 0x4c, 0x71, 0xcc, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x49, 0x49, 0xcc, 0xcb, 0x4c, 0xcd, 0x81, 0xf0, 0xf4, 0x8a, 0x20, 0x2a, 0xa4, 0x78, 0x9c,
	0xf3, 0x73, 0x73, 0xf3, 0xf3, 0x20, 0xa2, 0x4a, 0xad, 0x8c, 0x5c, 0x82, 0xee, 0xa9, 0x25, 0x70,
	0xed, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xd6, 0x5c, 0x6c, 0x19, 0xa9, 0x89, 0x29, 0xa9, 0x45,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xca, 0x7a, 0xd8, 0x8c, 0xd2, 0x83, 0x2a, 0xf7, 0x00,
	0x2b, 0x0d, 0x82, 0x6a, 0x11, 0x12, 0xe7, 0x62, 0x4f, 0x49, 0x4d, 0xcc, 0x89, 0xcf, 0x4c, 0x91,
	0x60, 0x52, 0x60, 0xd4, 0x60, 0x09, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x84, 0xa4, 0xb8, 0x38, 0x8a,
	0x52, 0x13, 0x73, 0x42, 0x32, 0x73, 0x53, 0x25, 0x98, 0x15, 0x18, 0x35, 0x38, 0x82, 0xe0, 0x7c,
	0xa5, 0xa9, 0x8c, 0x5c, 0x42, 0xc8, 0xee, 0x28, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0xb2, 0x41,
	0x73, 0x88, 0x0a, 0x2e, 0x87, 0x40, 0xd4, 0xa3, 0xb9, 0xc4, 0x91, 0x8b, 0x03, 0x6c, 0x75, 0x5e,
	0x5a, 0x3e, 0xd8, 0x29, 0xdc, 0x46, 0xaa, 0xb8, 0xf4, 0x83, 0x69, 0x17, 0xa8, 0xe2, 0x20, 0xb8,
	0x36, 0xa3, 0x2a, 0x2e, 0x5e, 0x94, 0xa0, 0x15, 0xca, 0x44, 0x76, 0x27, 0x4c, 0x83, 0x90, 0x3a,
	0x76, 0x73, 0x31, 0x42, 0x56, 0x4a, 0x83, 0xb0, 0x42, 0x88, 0x57, 0x94, 0x18, 0x92, 0xd8, 0xc0,
	0x6a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x17, 0xf9, 0x14, 0xaa, 0xdd, 0x01, 0x00, 0x00,
}
